# version: '3.8'

# services:
#   mongo:
#     image: mongo:latest
#     container_name: mongo
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongodb-data:/data/db

#   backend:
#     build: .
#     image: backend-app
#     ports:
#       - "8080:8080"
#     depends_on:
#       - mongo
#     environment:
#       - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/backend
#     volumes:
#       - ./target:/usr/local/app

# volumes:
#   mongodb-data:
#     driver: local
